CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	name TEXT NOT NULL,
	company TEXT NOT NULL,
	email TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS prompt_completions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	prompt TEXT NOT NULL,
	generated_text TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS generated_images (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	email TEXT NOT NULL,
	image_url TEXT NOT NULL,
	printed BOOLEAN DEFAULT FALSE NOT NULL,
	file_name TEXT DEFAULT ''
);
